### PR TITLE
ExpectSelfie and pytest integration

### PR DESCRIPTION
**Pull request by hssahota2**

### CODE REVIEW

**Comment by nedtwigg** [comment]
I can't push to your branch (some cruft to do with selfie-python-wip). But I pushed up some help, pull it down and push it back up to this PR

- https://github.com/diffplug/selfie/tree/tips-for-harvir

**Comment by nedtwigg** [comment]
There we go, thanks for giving me access :)

**Comment by nedtwigg** [comment]
Great progress! Looks like most of the major systems are superficially hooked up. The main issues I see are

- replacing stubs with the actual systems we developed in the previous epics, e.g. `CommentTracker`, `InlineWriteTracker`, etc.
- those systems should live inside `SnapshotSystem`, right now a lot of code paths seem to avoid `SnapshotSystem`, but everything should go through it

**Comment by hssahota2** [comment]
I've pushed my latest changes but I'm unsure on the next steps.

**Comment by nedtwigg** [comment]
Great work! I will take a look tonight.

**Comment by hssahota2** [comment]
Is it too late to create a new fork from diffplug/selfie and delete my current repo so that I don't have any conflicts?

**Comment by nedtwigg** [comment]
python-publish-doc is failing because you are pushing a branch called "main", but only "diffplug/selfie" has the auth token for publishing the docs. We can safely ignore it. In the future, work on a feature branch, not main.

This PR is great! There is lots left to do, but I am inclined to merge it so that your teammates can start to tinker with their hunks of this. Is that okay with you @hssahota2 ?

**Comment by hssahota2** [comment]
Yeah sounds good.

**Pull request merged**
